// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: login.sql

package sqlc

import (
	"context"
)

const devSeedLogin = `-- name: DevSeedLogin :exec
INSERT INTO logins (name, api_key)
VALUES ('Test User', '9c2320fa97aa6a17b35e01db9bcc0b251898dc5a95178bbb0ee1dde4dc4a7accba8f7746573a6869f68554f07d2ac2885d4b4b0afe9f544d474f31b89ff6ccbb')
`

func (q *Queries) DevSeedLogin(ctx context.Context) error {
	_, err := q.db.Exec(ctx, devSeedLogin)
	return err
}

const getLoginByApiKey = `-- name: GetLoginByApiKey :one
UPDATE logins
SET used_at = NOW()
WHERE api_key = $1
RETURNING id, api_key
`

type GetLoginByApiKeyRow struct {
	ID     int32
	ApiKey string
}

func (q *Queries) GetLoginByApiKey(ctx context.Context, apiKey string) (GetLoginByApiKeyRow, error) {
	row := q.db.QueryRow(ctx, getLoginByApiKey, apiKey)
	var i GetLoginByApiKeyRow
	err := row.Scan(&i.ID, &i.ApiKey)
	return i, err
}
