// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: measurement.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertMeasurement = `-- name: InsertMeasurement :exec
INSERT INTO measurements (sensor_id, temperature, cpu, time)
VALUES ($1, $2, $3, $4)
`

type InsertMeasurementParams struct {
	SensorID    int32
	Temperature float64
	Cpu         *float64
	Time        pgtype.Timestamptz
}

func (q *Queries) InsertMeasurement(ctx context.Context, arg InsertMeasurementParams) error {
	_, err := q.db.Exec(ctx, insertMeasurement,
		arg.SensorID,
		arg.Temperature,
		arg.Cpu,
		arg.Time,
	)
	return err
}
