// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Login struct {
	ID     int32
	Name   string
	ApiKey string
	UsedAt pgtype.Timestamptz
}

type Measurement struct {
	Time        pgtype.Timestamptz
	SensorID    int32
	Temperature float64
	Cpu         *float64
}

type Sensor struct {
	ID       int32
	Name     string
	Location string
	Unit     string
	ApiKey   string
}
