// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sensor.sql

package sqlc

import (
	"context"
)

const devSeedSensor = `-- name: DevSeedSensor :exec
INSERT INTO sensors (name, location, unit, api_key)
VALUES ('Test Sensor', 'Test Location', '°C', '9c2320fa97aa6a17b35e01db9bcc0b251898dc5a95178bbb0ee1dde4dc4a7accba8f7746573a6869f68554f07d2ac2885d4b4b0afe9f544d474f31b89ff6ccbb')
`

func (q *Queries) DevSeedSensor(ctx context.Context) error {
	_, err := q.db.Exec(ctx, devSeedSensor)
	return err
}

const getAllSensors = `-- name: GetAllSensors :many
SELECT
    s.id,
    s.name,
    s.location,
    s.unit,
    -- Create JSON object of the latest measurement
    json_build_object(
        'temperature', m.temperature,
        'cpu', m.cpu,
        'time', m.time
    ) AS latest_measurement
FROM sensors s
LEFT JOIN LATERAL (
    SELECT time, sensor_id, temperature, cpu
    FROM measurements m
    WHERE m.sensor_id = s.id
    ORDER BY m.time DESC
    LIMIT 1
) m ON true
`

type GetAllSensorsRow struct {
	ID                int32
	Name              string
	Location          string
	Unit              string
	LatestMeasurement []byte
}

func (q *Queries) GetAllSensors(ctx context.Context) ([]GetAllSensorsRow, error) {
	rows, err := q.db.Query(ctx, getAllSensors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSensorsRow
	for rows.Next() {
		var i GetAllSensorsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Location,
			&i.Unit,
			&i.LatestMeasurement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSensorByApiKey = `-- name: GetSensorByApiKey :one
SELECT id, api_key FROM sensors WHERE api_key = $1 LIMIT 1
`

type GetSensorByApiKeyRow struct {
	ID     int32
	ApiKey string
}

func (q *Queries) GetSensorByApiKey(ctx context.Context, apiKey string) (GetSensorByApiKeyRow, error) {
	row := q.db.QueryRow(ctx, getSensorByApiKey, apiKey)
	var i GetSensorByApiKeyRow
	err := row.Scan(&i.ID, &i.ApiKey)
	return i, err
}
